runtime: java17
inbound_services:
- warmup
auto_id_policy: default
handlers:
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /selected-post
  script: unused
  login: optional
  secure: optional
- url: /register
  script: unused
  login: optional
  secure: optional
- url: /message
  script: unused
  login: optional
  secure: optional
- url: /index
  script: unused
  login: optional
  secure: optional
- url: /password
  script: unused
  login: optional
  secure: optional
- url: /AdminServlet
  script: unused
  login: optional
  secure: optional
